
a = input()
d = {"WBWBWWBWBWBWWBWBWWBW": "Do", 
  "WBWWBWBWBWWBWBWWBWWB" : "Re",
  "WWBWBWBWWBWBWWBWWBWB" : "Mi",
  "WBWBWBWWBWBWWBWWBWBW" : "Fa",
  "WBWBWWBWBWWBWWBWBWWB" : "SO",
  "WBWWBWBWWBWWBWBWWBWB" : "La",
  "WWBWBWWBWWBWBWWBWBWB" : "Si",
} 
print(d.get(a))
